name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
jobs:
  build_docs:
    name: Build LaTeX Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/main.tex
          work_in_root_file_dir: true
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-documentation
          path: docs/main.pdf
